apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-container
        image: mongo:latest
        resources:
          requests:
            memory: "1Gi"
            cpu: 1
